# Generated by Django 2.1.8 on 2019-04-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='is_adult',
            field=models.IntegerField(),
        ),
    ]
