# Generated by Django 2.1.8 on 2019-04-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMDB', '0002_auto_20190426_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birth_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='known_for_titles',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='actor',
            name='primary_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='actor',
            name='primary_profession',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='original_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='primary_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title_type',
            field=models.CharField(max_length=100),
        ),
    ]
