# Generated by Django 2.1.8 on 2019-04-26 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IMDB', '0003_auto_20190426_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieActorAssoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMDB.Actor')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMDB.Movie')),
            ],
        ),
    ]
